# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build jupyter book

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -U jupyter-book
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build book
      run: |
        jb build ./guide
    - name: Publish generated content to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: guide/_build/html # The folder the action should deploy.
