name: Build Jupyter Book

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: jupyter/minimal-notebook

    steps:
    - name: Checkout action
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U jupyter-book
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build book
      run: |
        jb build ./guide
